trigger: none

stages:
- stage: DEV
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: Go@0
        displayName: Test WebApp
        inputs:
          command: test
          arguments: -v
          workingDirectory: 
      - task: Go@0
        displayName: Build WebApp
        inputs:
          command: build
          arguments: -v -o $(Build.ArtifactStagingDirectory)/simpleGolangWebApp
          workingDirectory: 
      - task: CopyFiles@2
        displayName: Copy static sites
        inputs:
          contents: 'static/**'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        displayName: Copy templates
        inputs:
          contents: 'templates/**'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: SimpleWebApp-Linux
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
      - task: Go@0
        displayName: Test WebApp
        inputs:
          command: test
          arguments: -v
          workingDirectory: 
      - task: Go@0
        displayName: Build WebApp
        inputs:
          command: build
          arguments: -v -o $(Build.ArtifactStagingDirectory)/simpleGolangWebApp.exe
          workingDirectory: 
      - task: CopyFiles@2
        displayName: Copy static sites
        inputs:
          contents: 'static\**'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        displayName: Copy templates
        inputs:
          contents: 'templates\**'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: SimpleWebApp-Windows
