# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DEV
  jobs:
  - job: Start WebApp
    steps:
      - script: starting WebApp
      - script: WebApp started
- stage: INT
  jobs:
  - job: Start WebApp
    steps:
      - script: starting WebApp
      - script: WebApp started
