trigger: none

stages:
- stage: DEV
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: Go@0
        inputs:
          command: test
          arguments: -v
          workingDirectory: 
      - task: Go@0
        inputs:
          command: build
          arguments: -v
          workingDirectory: 
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
      - task: Go@0
        inputs:
          command: test
          arguments: -v
          workingDirectory: 
      - task: Go@0
        inputs:
          command: build
          arguments: -v
          workingDirectory: 